version: '3'

services:
  remotevmix-apache:
    image: php:8.0-apache
    container_name: remotevmix-apache
    volumes:
        - ./:/var/www/html/
        - ./config/prod/apache2/conf-available/swag.conf:/etc/apache2/conf-available/swag.conf
        - ./config/prod/apache2/sites-enabled:/etc/apache2/sites-enabled/
        - ./config/prod/apache2/apache2.conf:/etc/apache2/apache2.conf
        - ./log:/var/log/apache2
    restart: unless-stopped
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on: 
      - remotevmix-db
    hostname: remotevmix-apache
     # command: a2enmod rewrite  && a2enmod remoteip && a2enconf swag && docker-php-ext-install pdo pdo_mysql && /etc/init.d/apache2 restart 
    networks: 
      - remotevmix_apache
      - remotevmix_db
 
  remotevmix-db:
    image: mariadb:latest
    container_name: remotevmix-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./db:/var/lib/mysql
    restart: unless-stopped
    hostname: remotevmix-db
    networks: 
      - remotevmix_db

networks:
  remotevmix_apache:
    name: remotevmix_apache
  remotevmix_db:
    name: remotevmix_db
