name: dockerhub_demo

on:
  push:
    branches:  
      - demo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '14'
  
      - name: Install Sass
        run: npm install -g sass
  
      - name: Compile SCSS
        run: |
          sass app/public/assets/style/index.scss app/public/assets/style/index.css
  
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg NODE_ENV=demo --tag vincentberry/vmix-remote:demo 
        
      - name: Docker Push
        run: docker push --all-tags vincentberry/vmix-remote